### ISSUE TITLE
Version 1.2.4 is not working

### ISSUE THREAD

**Issue by drsasapavlovic** [Khang-NT/Listen-2-Youtube#137]
After online update (ver. 123a) and loading libraries, crashes again!
I can't put error log because there is not such file in this version, in folder files.

**Comment by drsasapavlovic** [comment]
> Starting progress...
> Detect cpu architecture: arm64-v8a
> Checking required files...
Not found
> Start download library files: arm64-v8a-libs.zip
Cache dir: /data/data/com.kapp.youtube/cache
Created temp file libs695853502zip
Downloading...
Download complete
> Check sum library files
Getting md5 sum...
Origin file    : e68e223a65bf92bea657facbf190890f
Downloaded file: e68e223a65bf92bea657facbf190890f
Check hash sum success
> Unzip library files...
Unzip success
Delete temp file true
> Testing library...
Error, stack trace:
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kapp.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kapp.youtube-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libvlcjni.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:378)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:210)
	at com.kapp.youtube.view.fragment.LoadLibFragment.doTestLibrary(LoadLibFragment.java:179)
	at com.kapp.youtube.view.fragment.LoadLibFragment.doUnzipFile(LoadLibFragment.java:399)
	at com.kapp.youtube.view.fragment.LoadLibFragment.access$600(LoadLibFragment.java:56)
	at com.kapp.youtube.view.fragment.LoadLibFragment$5.onResponse(LoadLibFragment.java:356)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:831)

> Try to copy library files to /data/app/com.kapp.youtube-%d/lib/arm64/
> Checking root access...

**Comment by Khang-NT** [comment]
What happen after
> Checking root access...

If your phone is not rooted, It should be download a apk which already include library files in itself

**Comment by drsasapavlovic** [comment]
My phone is rooted (i noticed that in our conversation before). After
cheking root access, supersu gave access to the app, and after that it
craches.
27.06.2016. 03:05 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
after crash, it can be reopen?

**Comment by drsasapavlovic** [comment]
No
27.06.2016. 03:28 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
Please send me error log (*.stacktrace) in folder:
`/data/data/com.kapp.youtube/files/`

And check if these files are existing in folder:
`/data/app/com.kapp.youtube-?a number? /lib/arm64/`

1. libvlc.so
2. libvlcjni.so

If it not work, install another one:
https://youtube-app-d1576.firebaseapp.com/api/v1/youtube-music.apk

**Comment by Khang-NT** [comment]
Please let me know ?a number? in the path below in your phone

**Comment by drsasapavlovic** [comment]
There is not .stacktrace in this folder.
Files 1. and 2. are existing.
Were is the number, path below?
27.06.2016. 03:35 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by drsasapavlovic** [comment]
Not working
27.06.2016. 03:35 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
Okey, please help me test this build.
Uninstall current version first!
https://drive.google.com/open?id=0B1-d3Xs9yeFHWTlMOXh4c2xjVWc

**Comment by drsasapavlovic** [comment]
Crashes after downloadind libraries and force close when i try to open it.
27.06.2016. 10:39 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
Hard to guess what happen, I check all my code, it looks ok.
Hmm. No error log.
I will try to test some case...

**Comment by Khang-NT** [comment]
I changed code a lot. Please try it and show me what happened.
https://drive.google.com/open?id=0B1-d3Xs9yeFHcFNvQmh6WkFBZkU

**Comment by drsasapavlovic** [comment]
The downloading process wasn't finished (0%), but it sims the app is
working, exept converting to mp3 is to long.
27.06.2016. 05:04 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
I use 3rd party to fetch mp3 link, so it depends on them a lot...
Please help me test this version:
https://drive.google.com/file/d/0B1-d3Xs9yeFHcHVoeEtGTVhWWTA/view?usp=sharing

**Comment by drsasapavlovic** [comment]
Crashes and force close.
28.06.2016. 04:39 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by drsasapavlovic** [comment]
> Starting progress...
> Detect cpu architecture: arm64-v8a
> Checking required files...
Not found
> Start download library files: arm64-v8a-libs.zip
Cache dir: /data/data/com.kapp.youtube/cache
Created temp file libs695853502zip
Downloading...
Download complete
> Check sum library files
Getting md5 sum...
Origin file    : e68e223a65bf92bea657facbf190890f
Downloaded file: e68e223a65bf92bea657facbf190890f
Check hash sum success
> Unzip library files...
Unzip success
Delete temp file true
> Testing library...
Error, stack trace:
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kapp.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kapp.youtube-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libvlcjni.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:378)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:210)
	at com.kapp.youtube.view.fragment.LoadLibFragment$4.run(LoadLibFragment.java:207)
	at java.lang.Thread.run(Thread.java:831)

> Try to copy library files to /data/app/com.kapp.youtube-1/lib/arm64
> This folder is under system path, require root access!
> Checking root access...
OK
> Copying library file...
libvlc.so success
libvlcjni.so success
> Testing library...

**Comment by Khang-NT** [comment]
Does it work after "test library..."

**Comment by drsasapavlovic** [comment]
No
28.06.2016. 12:43 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
Hmm. Please test this one:
https://drive.google.com/open?id=0B1-d3Xs9yeFHcHVoeEtGTVhWWTA

**Comment by drsasapavlovic** [comment]
Not working
28.06.2016. 03:31 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
It crashes while trying to load library.
Then it "force close" whenever you reopen?

**Comment by Khang-NT** [comment]
Okey, after all... My idea is just copy library file to right place, and this place depends on cpu type of each devices , so please use Root Explorer and manual unzip library files download here:
https://youtube-app-d1576.firebaseapp.com/api/v1/arm64-v8a/libs.zip

To folder:
`/data/data/com.kapp.youtube/lib`

and try re-open app again!

if it still crashing.
Unzip library files to folder:
`/data/app/com.kapp.youtube/lib/arm64/`

**Comment by drsasapavlovic** [comment]
Yes
28.06.2016. 04:30 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
Hey, thanks for your support. I have new build here, please help me test:
https://drive.google.com/file/d/0B1-d3Xs9yeFHdVhLSTFrRlpHcTg/view?usp=sharing

if it continues to not work, I have to deploy a dedicated version for arm64 devices.

**Comment by drsasapavlovic** [comment]
Not working. Crashes after libraries download.
30.06.2016. 02:16 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
Then it crashes whenever you re-open it from Home screen
OR
It doesn't crash but It loads library from the beginning?

**Comment by drsasapavlovic** [comment]
After reopen force close (it wan't open). After installing, it craches
after loading libraries.

30.06.2016. 02:40 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
Okey, so a special build for your device (arm64) here, can you test it:
https://drive.google.com/file/d/0B1-d3Xs9yeFHOFROYXE4ekZxQlE/view?usp=sharing

**Comment by drsasapavlovic** [comment]
The special biuld app is ok!
Regards
30.06.2016. 04:47 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by drsasapavlovic** [comment]
One more thing. Big downloaded files (90 MB) are not visible in the app
(downloaded files).
30.06.2016. 04:47 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by chuchito04** [comment]
Thanks i have the same issue that drsaaapavlovic but with this special edition was solved, my processor is arm64 too thanks

**Comment by Khang-NT** [comment]
> One more thing. Big downloaded files (90 MB) are not visible in the app (downloaded files).  

Is the download success?
The destination file exists in download folder?

**Comment by drsasapavlovic** [comment]
Yes
01.07.2016. 04:06 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:
