### ISSUE TITLE
apk size

### ISSUE THREAD

**Issue by ertmuirm** [Khang-NT/Listen-2-Youtube#3]
why is apk so large? >90mb installed 
also this is not an xposed module per se,  why must it under the xposed repo?

**Comment by tonylost** [comment]
Size is because the developer has compiled the program for all cpu architectures in a single file. Certainly if done separately it get smaller files.
It is seen that Xposed does not recognize it as a module. I have no idea why the developer has placed at the Xposed repository.

**Comment by Kimmax** [comment]
Xposed wouldn't even needed if done correctly. Looks like the developer uses xposed like an appstore

**Comment by Khang-NT** [comment]
See my new updates guys! :100:
