### ISSUE TITLE
MD5 incorrect 

### ISSUE THREAD

**Issue by andreasf93** [Khang-NT/Listen-2-Youtube#4]
Can't install using xposed, I get md5 mismatch error.

**Comment by Khang-NT** [comment]
What apk file you have downloaded guy? I will check soon, but I think you should re-download apk file.

**Comment by Khang-NT** [comment]
Please download via Drive, because Xposed limit apk size at 8MB.
## Install:
  - [Download APK](https://drive.google.com/folderview?id=0B1-d3Xs9yeFHVnJlSFRITnlkZ2s&usp=sharing) file suit with your device's processor archiecture:
      - [armeabi-v7a](https://drive.google.com/file/d/0B1-d3Xs9yeFHMkRzV3Fxc3ZIQ0U/view?usp=sharing)  
      md5: 9e7acba42191187409c9098e22449b73
      - [arm64-v8a](https://drive.google.com/file/d/0B1-d3Xs9yeFHWncxNUhQbk00dVU/view?usp=sharing)  
      md5: 40db467b5b1a5b16395ddb9fc9b55dd4
      - [x86](https://drive.google.com/file/d/0B1-d3Xs9yeFHX0VlMHROR3lSUFE/view?usp=sharing)  
      md5: 7037e0f55aae599c13a7de4e14b7724a
      - [x86_64](https://drive.google.com/file/d/0B1-d3Xs9yeFHR19IcDJKZ1JacFE/view?usp=sharing)  
      md5: f0b8729108b77dfa65dc4df591112441
      - [mips](https://drive.google.com/file/d/0B1-d3Xs9yeFHR3RjdHJ2aTAtdWM/view?usp=sharing)  
      md5: 8647c5cae3a762696783f905ba133fca
      - Or [All in one .apk](https://drive.google.com/file/d/0B1-d3Xs9yeFHSDNMNXdZUERCbjg/view?usp=sharing)  
      md5: dd68f327aaa7441c894dfbbae5d58996
  - Xposed repo: http://repo.xposed.info/module/com.kapp.listen2youtube

**Comment by drsasapavlovic** [comment]
To avoid downloading trouble, change: /storage/emulated/0/Music 
to:
/storage/emulated/0/Download
