### ISSUE TITLE
codec used, readability of titel

### ISSUE THREAD

**Issue by omegades** [Khang-NT/Listen-2-Youtube#5]
When the video is converted to audio it uses some webm codec which cannot be skipped ahead in most audio players. Can you change the codec?

Also the readability of the title when a search query has been made is almost unreadable.

Thanks for your work!

**Comment by Khang-NT** [comment]
1. No, I didn't change codec. Youtube provides DASH audio stream which uses Opus (or Vorbis) codec, default player can't play this file type, but VLC is supporting.
VLC project: https://code.videolan.org/videolan/vlc-android/tree/master
Compiled lib: https://github.com/mrmaffen/vlc-android-sdk

2. I think so, I will reduce text size to suitable with most screen resolution  in next version.

**Comment by omegades** [comment]
Is there no other codec possible? I already found out that vlc can skip
yes. Unfortunately VLC has no chromecast.

**Comment by Khang-NT** [comment]
May be I will add convert to mp3 feature in next version (require root permission)
